/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import modelo.Validar;
import modelo.Variables;
import static modelo.Variables.L_COD_AGE;

/**
 *
 * @author Gonzalo Cabrera
 */
public class Agencias extends javax.swing.JInternalFrame {

    Validar valida=new Validar();
    
 
    public Agencias() {
        initComponents();
        
       valida.soloNumeros(txtCodAgencia);
       valida.limitarCaracteres(txtCodAgencia, L_COD_AGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodAgencia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomAgencia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCodBodega = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Actualiza Agencias");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Codigo");

        txtCodAgencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodAgenciaFocusGained(evt);
            }
        });
        txtCodAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodAgenciaActionPerformed(evt);
            }
        });
        txtCodAgencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodAgenciaKeyPressed(evt);
            }
        });

        jLabel2.setText("Nombre");

        txtNomAgencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomAgenciaFocusGained(evt);
            }
        });
        txtNomAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomAgenciaActionPerformed(evt);
            }
        });
        txtNomAgencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomAgenciaKeyPressed(evt);
            }
        });

        jLabel3.setText("Codigo bodega");

        txtCodBodega.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodBodegaFocusGained(evt);
            }
        });
        txtCodBodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodBodegaActionPerformed(evt);
            }
        });
        txtCodBodega.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodBodegaKeyPressed(evt);
            }
        });

        btnGuardar.setText("Aceptar");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodBodega, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCodBodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodAgenciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodAgenciaFocusGained
        // TODO add your handling code here:
        this.txtCodAgencia.selectAll();
    }//GEN-LAST:event_txtCodAgenciaFocusGained

    private void txtCodAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodAgenciaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCodAgenciaActionPerformed

    private void txtCodAgenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodAgenciaKeyPressed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_txtCodAgenciaKeyPressed

    private void txtNomAgenciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomAgenciaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomAgenciaFocusGained

    private void txtNomAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomAgenciaActionPerformed

    private void txtNomAgenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomAgenciaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomAgenciaKeyPressed

    private void txtCodBodegaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodBodegaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodBodegaFocusGained

    private void txtCodBodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodBodegaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodBodegaActionPerformed

    private void txtCodBodegaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodBodegaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodBodegaKeyPressed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        Variables.FRM_AGENCIAS=null;
    }//GEN-LAST:event_formInternalFrameClosing

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCodAgencia;
    private javax.swing.JTextField txtCodBodega;
    private javax.swing.JTextField txtNomAgencia;
    // End of variables declaration//GEN-END:variables
}
