/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import modelo.VO.AgenciaVO;
import modelo.VO.FacturaVO;
import modelo.FiltrarTablas;
import modelo.VO.PdvVO;
import modelo.DAO.AgenciaDAOImpl;
import modelo.DAO.FacturaDAOImpl;
import modelo.DAO.PdvDAOImpl;
import modelo.Validar;
import modelo.Variables;
import org.json.JSONArray;

/**
 *
 * @author Usuario
 */
public class BuscaFactura extends javax.swing.JDialog {

    Validar valida = new Validar();
    DefaultTableModel dtmFacturas;
    DecimalFormat formatoDecimal = new DecimalFormat("###,###,##0.00");
    FiltrarTablas filtraTabla;
    int numFactura;
    String mClave_fe, mConsecutivo_fe, mTipoDoc, mTipoFac, mNotas;
    int mPlazoCre, valorRetorno;
    double mTotExento, mTotGravado, mSubTotalFac, mDesctoFac, mImptoFac, mTotalFac;
    JSONArray jsonItems;

    public BuscaFactura(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();

        valida.limitarCaracteres(txtCodAge, Variables.L_COD_AGE);
        valida.soloNumeros(txtCodAge);
        valida.soloNumeros(txtCodPdv);
        valida.limitarCaracteres(txtCodPdv, Variables.L_COD_PDV);
        filtraTabla = new FiltrarTablas();

        txtCodAge.setText(String.valueOf(Variables.mAGEUSU));
        lblNomAge.setText(Variables.mNOMAGEUSU);
        txtCodPdv.setText(String.valueOf(Variables.mPDVUSU));
        lblNomPdv.setText(Variables.mNOMPDVUSU);
        if (Variables.mTIPOUSU < 4) {
            this.txtCodAge.setEnabled(false);
            this.txtCodPdv.requestFocus();
        }
        if (Variables.mTIPOUSU == 1) {
            txtCodPdv.setEnabled(false);
            jdcFecFactura.requestFocus();
        }
        Date fecha = new Date();
        jdcFecFactura.setDate(fecha);

        llenarTabla();

        jtFacturas.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent mouse_evt) {
                if (mouse_evt.getClickCount() == 2) {
                    seleccionaFactura();
                }
            }
        });
    }

    public int getNumFactura() {

        return valorRetorno;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        txtCodAge = new javax.swing.JTextField();
        lblNomAge = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCodPdv = new javax.swing.JTextField();
        lblNomPdv = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtFacturas = new javax.swing.JTable();
        jdcFecFactura = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();

        setTitle("Buscar factura");

        jLabel13.setText("Agencia");

        txtCodAge.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodAgeFocusGained(evt);
            }
        });
        txtCodAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodAgeActionPerformed(evt);
            }
        });
        txtCodAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodAgeKeyTyped(evt);
            }
        });

        lblNomAge.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel14.setText("Ruta/ Pdv");

        txtCodPdv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodPdvFocusGained(evt);
            }
        });
        txtCodPdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodPdvActionPerformed(evt);
            }
        });

        lblNomPdv.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jtFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cons.Interno", "Numero FE / Nombre", "Monto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtFacturas);
        if (jtFacturas.getColumnModel().getColumnCount() > 0) {
            jtFacturas.getColumnModel().getColumn(0).setResizable(false);
            jtFacturas.getColumnModel().getColumn(0).setPreferredWidth(10);
            jtFacturas.getColumnModel().getColumn(1).setResizable(false);
            jtFacturas.getColumnModel().getColumn(1).setPreferredWidth(300);
            jtFacturas.getColumnModel().getColumn(2).setResizable(false);
            jtFacturas.getColumnModel().getColumn(2).setPreferredWidth(20);
        }

        jLabel1.setText("Fecha");

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnImprimir.setText("Selecciona");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel2.setText("Buscar");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCodPdv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodAge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNomAge, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNomPdv, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jdcFecFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txtCodAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNomAge, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(txtCodPdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNomPdv, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jdcFecFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodAgeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodAgeFocusGained
        // TODO add your handling code here:
        this.txtCodAge.selectAll();
    }//GEN-LAST:event_txtCodAgeFocusGained

    private void txtCodAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodAgeActionPerformed
        // TODO add your handling code here:

        try {
            consultarAgencia();
        } catch (SQLException ex) {
            Logger.getLogger(BuscaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtCodAgeActionPerformed

    private void txtCodAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodAgeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodAgeKeyTyped

    private void txtCodPdvFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodPdvFocusGained
        // TODO add your handling code here:
        this.txtCodPdv.selectAll();
    }//GEN-LAST:event_txtCodPdvFocusGained

    private void txtCodPdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodPdvActionPerformed

        if (this.txtCodPdv.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar un codigo de PDV/Ruta");
            this.txtCodPdv.requestFocus();
            return;
        }
        try {
            consultarPdv();
        } catch (SQLException ex) {
            Logger.getLogger(BuscaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtCodPdvActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            llenarTabla();
        } catch (SQLException ex) {
            Logger.getLogger(BuscaFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased

        filtraTabla.filtro(txtBuscar.getText(), jtFacturas, 1);
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed

        seleccionaFactura();

    }//GEN-LAST:event_btnImprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcFecFactura;
    private javax.swing.JTable jtFacturas;
    private javax.swing.JLabel lblNomAge;
    private javax.swing.JLabel lblNomPdv;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodAge;
    private javax.swing.JTextField txtCodPdv;
    // End of variables declaration//GEN-END:variables

    private void consultarPdv() throws SQLException {
        PdvVO pdv = new PdvVO();
        pdv.setCodAgencia(Integer.valueOf(txtCodAge.getText()));
        pdv.setCodPdv(Integer.valueOf(txtCodPdv.getText()));

        if (PdvDAOImpl.consultar(pdv)) {

            this.lblNomPdv.setText(pdv.getNomPdv());
            if (txtCodAge.getText().length() > 0) {

            }
            jdcFecFactura.requestFocus();
        } else {
            JOptionPane.showMessageDialog(rootPane, "PDV/Ruta no existe");
            txtCodPdv.requestFocus();
        }

    }

    private void consultarAgencia() throws SQLException {
        AgenciaVO agencia = new AgenciaVO();
        agencia.setCodagencia(Integer.valueOf(txtCodAge.getText()));

        if (AgenciaDAOImpl.consultar(agencia)) {

            this.lblNomAge.setText(agencia.getNomagencia());
            if (txtCodPdv.getText().length() > 0) {

            }

            this.txtCodPdv.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "Agencia no existe");
            txtCodAge.requestFocus();
        }

    }

    private void llenarTabla() throws SQLException {
        dtmFacturas = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int i, int i1) {
                return false;
            }

        };
        // jtClientes=new JTable();       
        dtmFacturas.addColumn("Cons.Interno");
        dtmFacturas.addColumn("Numero FE / Nombre");
        dtmFacturas.addColumn("         Monto");

        // LLenamos el array desde la base de datos
        int age = Integer.valueOf(txtCodAge.getText());
        int pdv = Integer.valueOf(txtCodPdv.getText());
        SimpleDateFormat formatoYMD = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date fecha = jdcFecFactura.getDate();
        String sfecha = formatoYMD.format(fecha);

        ArrayList<FacturaVO> listaFacturas = FacturaDAOImpl.listarFacturas(age, pdv, sfecha);

        Object[] fila = new Object[3];
        for (int i = 0; i < listaFacturas.size(); i++) {
            fila[0] = listaFacturas.get(i).getNum_factura();
            fila[1] = listaFacturas.get(i).getConsecutivo_fe() + " " + listaFacturas.get(i).getNom_factura();
            Double monto = listaFacturas.get(i).getMon_subtotal() + listaFacturas.get(i).getMon_impto() - listaFacturas.get(i).getMon_descto();
            String sMonto = formatoDecimal.format(monto);
            fila[2] = sMonto;
            dtmFacturas.addRow(fila);
        }
        jtFacturas.setModel(dtmFacturas);

        DefaultTableCellRenderer dtcr = new DefaultTableCellRenderer();
        dtcr.setHorizontalAlignment(SwingConstants.RIGHT);

        jScrollPane1.setViewportView(jtFacturas);
        if (jtFacturas.getColumnModel().getColumnCount() > 0) {
            jtFacturas.getColumnModel().getColumn(0).setResizable(false);
            jtFacturas.getColumnModel().getColumn(0).setPreferredWidth(10);
            jtFacturas.getColumnModel().getColumn(1).setResizable(false);
            jtFacturas.getColumnModel().getColumn(1).setPreferredWidth(300);
            jtFacturas.getColumnModel().getColumn(2).setResizable(false);
            jtFacturas.getColumnModel().getColumn(2).setPreferredWidth(25);
            jtFacturas.getColumnModel().getColumn(2).setCellRenderer(dtcr);
        }

    }

    private void seleccionaFactura() {

        if (jtFacturas.getSelectedColumnCount() > 0) {
            int viewRow = jtFacturas.getSelectedRow();
            if (viewRow < 0) {
                valorRetorno = (int) dtmFacturas.getValueAt(viewRow, 0);
            } else {
                int modelRow = jtFacturas.convertRowIndexToModel(viewRow);
                valorRetorno = (int) dtmFacturas.getValueAt(modelRow, 0);
            }
            dispose();

        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una factura");
            jtFacturas.requestFocus();
        }

    }

}
